### ISSUE TITLE
uninitialized constant RubyLambda::Build::Bundler

### ISSUE THREAD

**Issue by scottwater** [cookieshq/ruby_lambda#1]
I love the idea of this project!

I was trying the bare minimal example:

```bash
gem install ruby_lambda
ruby-lambda init
ruby-lambda execute 
ruby-lambda build
```

The gem installs, init creates the files, and execute shows the sample JSON.

Build fails with: `uninitialized constant RubyLambda::Build::Bundler`

Full Trace: 
![Screen Shot on 2019-05-30 at 11-54-28](https://user-images.githubusercontent.com/188069/58645820-1515bd00-82d2-11e9-9965-c8361f789538.png)

I thought maybe I needed ruby_lambda in my Gem file, but that didn't fix the issue. 

I also changed was .ruby-version from 2.5.0 to 2.5.3 (already had it installed).

Any other suggestions? 

Thanks,
Scott

**Comment by denissellu** [comment]
Hey @scottwater, 

Thanks for giving the gem a try and spotting this! This commit (https://github.com/cookieshq/ruby_lambda/commit/32d0ea1ad91209d28d620ab76290db9f9a9efc06) includes bundler as a runtime dependency, so updating the gem will fix the issue for you.

cheers

**Comment by scottwater** [comment]
Perfect. That fixed my issue. Thanks!
