### ISSUE TITLE
Create ENV file as hidden

### ISSUE THREAD

**Issue by igbanam** [cookieshq/ruby_lambda#2]
Amazing work 🥳
I am yet to deploy something, but I am working towards that

As I initiated a new project, I saw…

```
    Created env
```

…but I looked for `env` and could not find it. So I looked through the code and saw that this file is getting renamed. This was slightly confusing to me. I looked further and saw `.env` in the `templates/.gitignore` so I thought leaving `env` as a filr tracked by git was useful to learn how this file evolves over time.

In other repos, I have seen an `env.sample` which is a mirror of the `.env` file necessary. This file is copied at build time into `.env`. Then the status can say something like…

```
    Created .env
```

…when this process is done.

What do you think?

p.s: This is not a breaking issue. It's just …UX, somewhat.

**Comment by denissellu** [comment]
@igbanam thanks for this, I think you are right, I always use .env locally, but allowing it to be in git and users to renaming how that would like is the better approach! 👍
